// <auto-generated />
using Jcm.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jcm.DAL.Migrations
{
    [DbContext(typeof(TalentContext))]
    [Migration("20240127103518_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("Jcm.DAL.Entities.PerformanceAct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PerformanceActs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "The Beatles"
                        },
                        new
                        {
                            Id = 2,
                            Name = "The Rolling Stones"
                        });
                });

            modelBuilder.Entity("Jcm.DAL.Entities.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceActId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceActId");

                    b.ToTable("Performers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            PerformanceActId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Paul",
                            PerformanceActId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "George",
                            PerformanceActId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ringo",
                            PerformanceActId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Mick",
                            LastName = "Jagger",
                            PerformanceActId = 2
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Keith",
                            LastName = "Richards",
                            PerformanceActId = 2
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Ron",
                            LastName = "Wood",
                            PerformanceActId = 2
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Bill",
                            LastName = "Wyman",
                            PerformanceActId = 2
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Charlie",
                            LastName = "Watts",
                            PerformanceActId = 2
                        });
                });

            modelBuilder.Entity("Jcm.DAL.Entities.Performer", b =>
                {
                    b.HasOne("Jcm.DAL.Entities.PerformanceAct", "PerformanceAct")
                        .WithMany("Performers")
                        .HasForeignKey("PerformanceActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformanceAct");
                });

            modelBuilder.Entity("Jcm.DAL.Entities.PerformanceAct", b =>
                {
                    b.Navigation("Performers");
                });
#pragma warning restore 612, 618
        }
    }
}
